SELECT * FROM academic_period;
SELECT * FROM competence;
SELECT * FROM environment;
SELECT * FROM period_program;
SELECT * FROM program;
SELECT * FROM program_competence;
SELECT * FROM schedule;
SELECT * FROM teacher;
SELECT * FROM user;